# Generated by Django 5.1.4 on 2025-02-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posts_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='category_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
